server:
  port: 2000
  servlet:
#    context-path: /authservice
    session:
      cookie:
        name: TUTORIALAUTHSESSION
    
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authdb
    username: root
    password: root