server:
  port: 2000
  servlet:
#    context-path: /authservice
    session:
      cookie:
        name: TUTORIALAUTHSESSION
    
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authdb
    username: root
    password: root
  application:
    name: authservice
    
    
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
security:
  oauth2:
    client:
      clientId: auth
      clientSecret: root
      scope:
        read
      accessTokenUri: http://localhost:2000/oauth/token
      userAuthorizationUri: http://localhost:2000/oauth/authorize
    resource:
      userInfoUri: http://localhost:2000/api/user
