#basicservice-container.yml
server:
  servlet:
    session:
      cookie:
        name: TUTORIALBASESESSION
spring:
  profiles: container
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASESERVER_PORT}/${DATABASE_NAME}?useSSL=false&serverTimezone=UTC
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    
security:
  oauth2:
    client:
      clientId: ${OAUTH2CLIENTID}
      clientSecret: ${OAUTH2CLIENTSECRET}
      scope:
        ${OAUTH2CLIENTSCOPE}
      accessTokenUri: ${AUTHENTICATIONSERVICE_CONTAINER_URI}/oauth/token
      userAuthorizationUri: ${AUTHENTICATIONSERVICE_URI}/oauth/authorize
    resource:
      userInfoUri: ${AUTHENTICATIONSERVICE_CONTAINER_URI}/api/user
      
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${DISCOVERY_URL}