#basicservice.yml
server:
  servlet:
    session:
      cookie:
        name: TUTORIALBASESESSION
spring:
  datasource:
    url: jdbc:mysql://localhost:3317/basicdb?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    
security:
  oauth2:
    client:
      clientId: basicService
      clientSecret: root
      scope:
        read
      accessTokenUri: http://localhost:2000/oauth/token
      userAuthorizationUri: http://localhost:2000/oauth/authorize
    resource:
      userInfoUri: http://localhost:2000/api/user
      
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/