server:
   port: 3000
spring:
  profiles:
    active: native
  cloud:
     config:
       server:
           native:
#               searchLocations: file:////Users/elvo/Documents/Projects/Courses/WebSecurity/springMicroServices/docker/configurationFiles/authenticationService,
#                                file:////Users/elvo/Documents/Projects/Courses/WebSecurity/springMicroServices/docker/configurationFiles/basicservice,
#                                file:////Users/elvo/Documents/Projects/Courses/WebSecurity/springMicroServices/docker/configurationFiles/discoveryservice                            
                               
                               
               searchLocations:
                               file:///configfiles/authenticationservice,
                               file:///configfiles/basicservice,
                               file:///configfiles/discoveryservice

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN